# Generated by Django 3.2.2 on 2022-02-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220224_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='market',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.market'),
        ),
    ]
