# Generated by Django 3.2.2 on 2022-02-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20220225_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='darsh_key',
            field=models.IntegerField(error_messages={'unique': 'darsh key is used'}, null=True, unique=True, verbose_name='darsh key'),
        ),
    ]
